apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base

images:
- name: frontend
  newName: ghcr.io/yuliakushnir/frontend-is-order
  newTag: 6f7b59ba00860387db0446b2de2aacd305be4772
- name: gateway-is-order
  newName: ghcr.io/yuliakushnir/gateway-is-order
  newTag: latest
- name: gateway-service
  newName: ghcr.io/yuliakushnir/gateway-is-order
  newTag: latest
- name: notification-service
  newName: ghcr.io/yuliakushnir/notification-service
  newTag: latest
- name: order-service
  newName: ghcr.io/yuliakushnir/order-service
  newTag: latest
- name: print-service
  newName: ghcr.io/yuliakushnir/print-service
  newTag: latest
- name: product-service
  newName: ghcr.io/yuliakushnir/product-service
  newTag: latest
- name: user-service
  newName: ghcr.io/yuliakushnir/user-service
  newTag: latest
