apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base

images:
- name: frontend
  newName: ghcr.io/yuliakushnir/frontend-is-order
  newTag: 3d8ee8168b09c16ed521418761968c72ff3c3b17
- name: gateway-is-order
  newName: ghcr.io/yuliakushnir/gateway-is-order
  newTag: latest
- name: gateway-service
  newName: ghcr.io/yuliakushnir/gateway-is-order
  newTag: latest
- name: notification-service
  newName: ghcr.io/yuliakushnir/notification-service
  newTag: latest
- name: order-service
  newName: ghcr.io/yuliakushnir/order-service
  newTag: 12396c01bfb2ddb1c57b6a0a2d51879129061c9e
- name: print-service
  newName: ghcr.io/yuliakushnir/print-service
  newTag: latest
- name: product-service
  newName: ghcr.io/yuliakushnir/product-service
  newTag: 98828cd4497c1c2df252c2fbfde160e75d28fcad
- name: user-service
  newName: ghcr.io/yuliakushnir/user-service
  newTag: 268cd60e339a4278b968b255827e2b84adab434a
