apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base

images:
- name: frontend
  newName: ghcr.io/yuliakushnir/frontend-is-order
  newTag: ab0c63ef5281005541a1de76e929ec497b169517
- name: gateway-is-order
  newName: ghcr.io/yuliakushnir/gateway-is-order
  newTag: a4687b56a83f6c7ce94e10c8cda3eb9577dc35b8
- name: gateway-service
  newName: ghcr.io/yuliakushnir/gateway-is-order
  newTag: latest
- name: notification-service
  newName: ghcr.io/yuliakushnir/notification-service
  newTag: latest
- name: order-service
  newName: ghcr.io/yuliakushnir/order-service
  newTag: 777a38ac75c9a8d51cc09164a08a5112a9b306b0
- name: print-service
  newName: ghcr.io/yuliakushnir/print-service
  newTag: latest
- name: product-service
  newName: ghcr.io/yuliakushnir/product-service
  newTag: latest
- name: user-service
  newName: ghcr.io/yuliakushnir/user-service
  newTag: latest
