apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: cloud-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ghcr.io/yuliakushnir/user-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: password

            - name: KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: realm
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: client-id
            - name: KEYCLOAK_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: username
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: password
            - name: $KEYCLOAK_TARGET_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: target-client-id

            - name: KEYCLOAK_HOST
              value: "keycloak"
            - name: KEYCLOAK_PORT
              value: "8181"

          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 40
            periodSeconds: 20
