apiVersion: apps/v1
kind: Deployment
metadata:
  name: print-service
  namespace: cloud-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: print-service
  template:
    metadata:
      labels:
        app: print-service
    spec:
      containers:
        - name: posts-service
          image: ghcr.io/yuliakushnir/print-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: password

            - name: KEYCLOAK_HOST
              value: "keycloak"
            - name: KEYCLOAK_PORT
              value: "8181"

          readinessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 40
            periodSeconds: 20
