apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: cloud-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: posts-service
          image: ghcr.io/yuliakushnir/order-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: password

            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: cloud-name
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: api-key
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: api-secret

            - name: KEYCLOAK_HOST
              value: "keycloak"
            - name: KEYCLOAK_PORT
              value: "8181"

#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8083
#            initialDelaySeconds: 40
#            periodSeconds: 10
#            timeoutSeconds: 5
#            failureThreshold: 6

#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8083
#            initialDelaySeconds: 90
#            periodSeconds: 20
#            timeoutSeconds: 5
#            failureThreshold: 6

          readinessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 50
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 150
            periodSeconds: 20
